Mon 11583 logv2 engine
centreon/centreon-collect pull request #114
Opened 2021-12-10 15:17 UTC by rem31

2022-01-10 15:13 UTC, bouda1 requested changes

2022-01-10 15:13 UTC, bouda1 commented on centreon-engine/src/events/sched_info.cc
> +      ctime(&scheduling_info.last_service_check));
All these previous lines contain too many '\n'

2022-01-10 15:13 UTC, bouda1 commented on centreon-engine/src/events/sched_info.cc
> +      ctime(&scheduling_info.last_service_check));
maybe we should call log_v2::process()->... several times, one for each desired line, or maybe it is better to format a single line with all the informations

2022-01-10 15:13 UTC, bouda1 commented on centreon-engine/src/events/sched_info.cc
> +  engine_logger(log_info_message, basic)
Be careful with logs in this file, too many '\n' to reformat

2022-01-10 15:13 UTC, bouda1 commented on centreon-engine/src/downtimes/service_downtime.cc
> +      get_triggered_by());
What to do with '\n'?

2022-01-10 15:13 UTC, bouda1 commented on centreon-engine/src/downtimes/service_downtime.cc
> +                                     << found->second->get_description();
Issues with '\n'

2022-01-10 15:13 UTC, bouda1 commented on centreon-engine/modules/external_commands/src/processing.cc
> +      "External command id: {} \nCommand entry time: {} \nCommand arguments: ",
{} missing

2022-01-10 15:13 UTC, bouda1 commented on centreon-engine/src/downtimes/host_downtime.cc
> +  engine_logger(dbg_downtime, basic)
What to do with '\n'?

2022-01-10 15:13 UTC, bouda1 commented on centreon-engine/src/downtimes/host_downtime.cc
> +      end_time_string, hours, minutes, get_downtime_id(), get_triggered_by());
issue with \n

2022-01-10 17:49 UTC, bouda1 requested changes

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/src/host.cc
> +      (get_state_type() == hard ? "HARD" : "SOFT"), get_current_state(),
parenthesis

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/src/host.cc
> +                              (get_state_type() == hard ? "HARD" : "SOFT"));
parenthesis

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/src/host.cc
> +      (get_state_type() == hard ? "HARD" : "SOFT"), _current_state);
parenthesis

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/src/host.cc
> +      (get_state_type() == hard ? "HARD" : "SOFT"), _current_state);
parenthesis

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/src/macros/process.cc
> +      input_buffer);
\n

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/src/macros/process.cc
> +              token.c_str(), token_resolved, clean_options, free_macro);
c_str() not needed

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/src/macros/process.cc
> +      output_buffer);
\n

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/src/main.cc
> +
std::cout looks better than log_v2 here. The goal of these messages is to display them in the terminal

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/src/main.cc
> +          argv[0]);
the same here

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/src/main.cc
> +            timeperiod::timeperiods.size(), config_warnings, config_errors);
same here I think

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/src/main.cc
> +               "files.\n\n" ERROR_CONFIGURATION;
to be display on stdout or stderr

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/src/main.cc
> +                << e.what();
idem here

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/src/notifier.cc
> +        "Error: Invalid notification_interval value for notifier '{}'");
variable missing

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/src/notifier.cc
> +        (_first_notification_delay * config->interval_length()));
parenthesis

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/src/notifier.cc
> +              (notification_interval * config->interval_length()));
missing variable

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/src/notifier.cc
> +          (get_last_hard_state_change() + _recovery_notification_delay));
parenthesis

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/tests/configuration/applier/applier-log.cc
> + * Copyright 2019 Centreon (https://www.centreon.com/)
2021

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/test/configuration/applier/xrddefault.cc
> +    engine_logger(dbg_retentiondata, most)
No log_v2?

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/test/configuration/applier/xrddefault.cc
> +      engine_logger(log_runtime_error, basic)
No log_v2?

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/test/configuration/applier/xrddefault.cc
> +  engine_logger(dbg_functions, basic) << "xrddefault_save_state_information()";
no log_v2?

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/test/configuration/applier/xrddefault.cc
> +    engine_logger(log_runtime_error, basic)
same

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/test/configuration/applier/xrddefault.cc
> +    engine_logger(log_runtime_error, basic)
same...

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/test/configuration/applier/xrddefault.cc
> +    engine_logger(log_runtime_error, basic)
same

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/test/configuration/applier/xodtemplate.cc
> +    engine_logger(log_config_error, basic)
no log_v2 in this file?

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/test/configuration/applier/events.cc
> +  log_v2::functions()->trace "init_timing_loop()"();
How this could compile?

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/src/service.cc
> +      (queued_check_result->get_exited_ok() ? "Yes" : "No"), execution_time,
too many parenthesis

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/src/service.cc
> +        (get_perf_data().empty() ? "NULL" : get_perf_data()));
\n

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/src/service.cc
> +                          (is_flapping ? "is" : "is not"),
parenthesis

2022-01-10 17:49 UTC, bouda1 commented on centreon-engine/src/service.cc
> +      (options & CHECK_OPTION_FORCE_EXECUTION ? "forced" : "non-forced"),
()

2022-01-11 16:21 UTC, rem31 commented on centreon-engine/test/configuration/applier/xodtemplate.cc
> +    engine_logger(log_config_error, basic)
is not compiled

2022-01-11 16:21 UTC, rem31 commented on centreon-engine/test/configuration/applier/xrddefault.cc
> +    engine_logger(log_runtime_error, basic)
is not compiled

2022-01-11 16:21 UTC, rem31 commented on centreon-engine/test/configuration/applier/xrddefault.cc
> +    engine_logger(log_runtime_error, basic)
is not compiled

2022-01-13 17:21 UTC, bouda1 requested changes

2022-01-13 17:21 UTC, bouda1 commented on centreon-engine/src/main.cc
> +      std::cout
Could you also remove the "<<" here pleaaaaaaaase?

2022-01-13 17:21 UTC, bouda1 commented on centreon-engine/src/main.cc
> +                  << "Total Errors:   " << config_errors << std::endl;
Here too, you can remove several "<<"

2022-01-13 17:21 UTC, bouda1 commented on centreon-engine/src/main.cc
> +                << e.what();
is it really needed?

2022-01-13 17:21 UTC, bouda1 commented on centreon-engine/src/main.cc
> +                      << std::endl;
should be a log_v2...

2022-01-13 17:21 UTC, bouda1 commented on centreon-engine/src/main.cc
> +        std::cout << e.what() << std::endl;
to check...

2022-01-14 08:17 UTC, rem31 commented on centreon-engine/modules/external_commands/src/processing.cc
> +  log_v2::external_command()->debug("Command arguments: {}", args);
is a debug log

2022-01-18 10:51 UTC, bouda1 commented on centreon-engine/src/commands/connector.cc
> +                            _name);
missing {}

2022-01-18 11:07 UTC, bouda1 approved these changes

2022-01-18 11:41 UTC, merged