fix(gorgone): Add missing centengine report part to centreon-storage database
centreon/centreon-collect pull request #1522
Opened 2024-07-10 13:48 UTC by kduret

## Description

Migrated from https://github.com/centreon/centreon/pull/4465

some of the poller performance report is missing since the gorgone migration.
This pr aim to add all data that was previously added in centreon-storage.

Fixes # MON-37990

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

2024-07-11 08:06 UTC, mushroomempires approved these changes

2024-07-16 15:25 UTC, omercier approved these changes

2024-07-17 09:55 UTC, sdepassio approved these changes

2024-07-19 15:34 UTC, tuntoja commented
shouldn t tests be green ?

2024-07-19 15:41 UTC, tuntoja approved these changes

2024-08-01 13:16 UTC, omercier approved these changes

2024-08-05 14:50 UTC, smau-centreon requested changes

2024-08-05 14:50 UTC, smau-centreon commented on .github/docker/Dockerfile.gorgone-testing-bookworm
> +# Install required lib for language and apt installation. zstd is required for cache management in GHA
```suggestion
# Install the required lib for language and apt installation. zstd is required for cache management in GHA.
```

2024-08-05 14:50 UTC, smau-centreon commented on .github/docker/Dockerfile.gorgone-testing-bookworm
> +# Install Robotframework and tests dependency
```suggestion
# Install Robotframework and test dependency
```

2024-08-05 14:50 UTC, smau-centreon commented on .github/docker/Dockerfile.gorgone-testing-bullseye
> +# Install required lib for language and apt installation. zstd is required for cache management in GHA
```suggestion
# Install the required lib for language and apt installation. zstd is required for cache management in GHA.
```

2024-08-05 14:50 UTC, smau-centreon commented on .github/docker/Dockerfile.gorgone-testing-bullseye
> +# Install Robotframework and tests dependency
```suggestion
# Install Robotframework and test dependency
```

2024-08-05 14:50 UTC, smau-centreon commented on gorgone/docs/modules/centreon/statistics.md
> +This module aims to deal with statistics collection of Centreon Engine and Broker. It require action module to be configured on each poller and on the central.
```suggestion
This module aims to manage the collection of Centreon Engine and Broker statistics. It requires the configuration of an action module on each poller and on the central.

```

2024-08-05 14:50 UTC, smau-centreon commented on gorgone/docs/modules/centreon/statistics.md
> +The configuration needs a cron definition to unsure that statistics collection will be done regulary.
```suggestion
The configuration needs a cron definition to ensure that statistics are collected regularly.

```

2024-08-05 14:50 UTC, smau-centreon commented on gorgone/docs/modules/centreon/statistics.md
> +The api send back a token to monitor advancement. Please note this token don't allow to monitor the whole process, only the first part until action command are sent.
```suggestion
The API returns a token to monitor the advancement. Please note this token does not allow to monitor the whole process but only the first part until an action command is sent.

```

2024-08-05 15:08 UTC, smau-centreon requested changes

2024-08-05 15:08 UTC, smau-centreon commented on gorgone/docs/modules/centreon/statistics.md
> +This module aims to manage the collection of Centreon Engine and Broker statistics. It require requires the configuration of an action module on each poller and on the central.
```suggestion
This module aims to manage the collection of Centreon Engine and Broker statistics. It requires the configuration of an action module on each poller and on the central.

```

2024-08-05 15:08 UTC, smau-centreon commented on gorgone/docs/modules/centreon/statistics.md
> +The configuration needs a cron definition to ensure that statistics collection are collected regularly.
```suggestion
The configuration needs a cron definition to ensure that statistics are collected regularly.

```

2024-08-05 15:50 UTC, smau-centreon approved these changes

2024-08-06 08:26 UTC, merged