enh(scheduler): add some info on debug log to Keeping original host c…
centreon/centreon-collect pull request #164
Opened 2022-03-03 13:56 UTC by jean-christophe81

add grpc module
add cbd link option to publish symbols for modules

REFS: MON-12283

2022-03-03 14:35 UTC, rem31 requested changes

2022-03-03 14:35 UTC, rem31 commented on centreon-broker/grpc/test/connector.cc
> +//   io->write(data);
why ?

2022-03-04 11:00 UTC, bouda1 approved these changes

2022-03-16 21:24 UTC, bouda1 commented on centreon-broker/grpc/CMakeLists.txt
> +## Copyright 2011 Centreon
2022

2022-03-16 21:24 UTC, bouda1 commented on centreon-broker/grpc/inc/com/centreon/broker/grpc/factory.hh
> + *  Build TCP protocol objects.
Bad comment

2022-03-16 21:24 UTC, bouda1 commented on centreon-broker/grpc/inc/com/centreon/broker/grpc/stream.hh
> +  // }
still needed?

2022-03-16 21:24 UTC, bouda1 commented on centreon-broker/grpc/test/grpc_test_keys/ca_1234.crt
> +BAYTAlNQMQ8wDQYDVQQIDAZGcmFuY2UxETAPBgNVBAcMCFRvdWxvdXNlMQ0wCwYD
Do you really need these certificates? Is it not possible to generate during the tests?

2022-03-16 21:24 UTC, bouda1 commented on centreon-broker/tcp/src/connector.cc
> +    throw;
We returned nullptr and not you throw an exception. Is this ok for you ?

2022-03-16 21:24 UTC, bouda1 commented on centreon-broker/test/test_util/CMakeLists.txt
> +## Copyright 2011 Centreon
2022

2022-03-16 21:26 UTC, bouda1 commented on centreon-broker/tcp/src/connector.cc
> +    throw;
Maybe this leads to the same result... I don't know, so I ask :smile:

2022-03-17 08:22 UTC, bouda1 approved these changes

2022-03-17 10:06 UTC, merged