Mon 13562 sonar atoi external command
centreon/centreon-collect pull request #302
Opened 2022-06-27 15:48 UTC by denliA

#REFS: MON-13562
remplace atoi by abseil::SimpleAtoi for external commands
some robot tests

## Description

Please include a short resume of the changes and what is the purpose of PR. Any relevant information should be added to help:
* **QA Team** (Quality Assurance) with tests.
* **reviewers** to understand what are the stakes of the pull request.

**Fixes** # (issue)

## Type of change

- [X] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 21.04.x
- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2022-07-04 09:25 UTC, bouda1 requested changes

2022-07-04 09:25 UTC, bouda1 commented on connectors/ssh/src/orders/options.cc
> +        _port = temp;
Please, encapsulate this code with {}

2022-07-04 09:25 UTC, bouda1 commented on engine/src/commands/commands.cc
> +  char* command_name(nullptr);
no need to initialize it. You make the work just after

2022-07-05 09:51 UTC, bouda1 requested changes

2022-07-05 09:51 UTC, bouda1 commented on tests/broker-engine/external-commands.robot
> +	Should Be True	${result}	msg=command argument persistent_flag must be 0 or 1.
Also add a call to DEL_SVC_COMMENT with wrong id (-1 for example).

2022-07-05 09:51 UTC, bouda1 commented on tests/broker-engine/external-commands.robot
> +	Should Be True	${result}	msg=command argument persistent_flag must be 0 or 1.
in the centreon_storage database, we have a table `comments` that can help you

2022-07-05 09:51 UTC, bouda1 commented on tests/resources/Engine.py
> +        now, hst, notification_option, author, comment)
you can use f""

2022-07-11 12:44 UTC, bouda1 requested changes

2022-07-11 12:44 UTC, bouda1 commented on engine/src/commands/commands.cc
> +  uint64_t internal_id = com->get_comment_id();
here, we are in engine, some let's keep the name comment_id

2022-07-11 12:47 UTC, jean-christophe81 approved these changes

2022-07-11 13:39 UTC, bouda1 approved these changes

2022-07-11 14:09 UTC, merged