chore(license): update maintainer and email addresses
centreon/centreon-collect pull request #530
Opened 2023-01-25 16:50 UTC by sc979

## Description

Update packaging licences' email addresse and maintainer

**Fixes** # (none)

## Type of change

- [x] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [x] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x (master)

2023-01-26 13:43 UTC, bouda1 requested changes

2023-01-26 13:43 UTC, bouda1 commented on ci/debian-gorgone/control
> +Maintainer: Centreon <contact@centreon.com>
Please remove this directory.
We do not manage gorgone here.

2023-01-26 13:43 UTC, bouda1 commented on ci/debian-gorgone/copyright
> +Upstream-Contact: Centreon <contact@centreon.com>
Same here.

2023-01-27 07:43 UTC, kduret approved these changes

2023-01-27 09:43 UTC, merged