Mon 16262 victoria metrics interprocess
centreon/centreon-collect pull request #703
Opened 2023-04-13 06:49 UTC by jean-christophe81

## Description

add victoria metrics output
it also include pb_metric and pb_status addition in influxdb and graphite output

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [X] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [X] 23.04.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2023-06-29 08:23 UTC, bouda1 requested changes

2023-06-29 08:23 UTC, bouda1 commented on broker/victoria_metrics/src/request.cc
> +        3) {  // we don't write unknow but it's not an error
```suggestion
        3) {  // we don't write unknown but it's not an error
```

2023-06-29 08:23 UTC, bouda1 commented on broker/victoria_metrics/test/factory_test.cc
> + * Copyright 2019 Centreon (https://www.centreon.com/)
```suggestion
 * Copyright 2022-2023 Centreon (https://www.centreon.com/)
```

2023-06-29 08:23 UTC, bouda1 commented on tests/broker-engine/victoria.robot
> +VICT_ONE_CHECK_METRIC
robotidy is not applied on this robot file.

2023-07-17 05:58 UTC, jean-christophe81 commented on broker/unified_sql/src/stream_sql.cc
> +    }
No, this object is only present int case of victoria metrics usage

2023-07-17 07:15 UTC, jean-christophe81 commented on broker/core/src/cache/global_cache.cc
> +  return nullptr;
_file is reopened in case of growth

2023-07-17 07:16 UTC, jean-christophe81 commented on broker/core/src/main.cc
> +#include "com/centreon/broker/cache/global_cache.hh"
because there are included in precomp

2023-07-17 09:37 UTC, jean-christophe81 commented on bbdo/storage.proto
> +  uint64 service_id = 7;
more efficient to transport this two numbers than search in a cache

2023-07-17 12:36 UTC, jean-christophe81 commented on packaging/rpm/centreon-collect.spec
> +generated by plugins (run themselves by Centreon Engine) to a influxdb
obsolete

2023-07-20 12:38 UTC, jean-christophe81 commented on broker/core/test/cache/global_cache_test.cc
> +TEST(global_cache_test, CanBeMoved) {
test fixed

2023-07-20 13:12 UTC, thearchit3ct commented on tests/broker-engine/victoria.robot
> +            ${metric_found}    check_victoria_metric
```suggestion
            ${metric_found}    Check Victoria Metric
```

2023-07-20 13:12 UTC, thearchit3ct commented on tests/broker-engine/victoria.robot
> +    ${result}    find_in_log_with_timeout    ${centralLog}    ${start}    ${content}    60
```suggestion
    ${result}    Find In Log With Timeout    ${centralLog}    ${start}    ${content}    60
```

2023-07-20 13:12 UTC, thearchit3ct commented on tests/broker-engine/victoria.robot
> +    ${start}    get_round_current_date
```suggestion
    ${start}    Get Round Current Date
```

2023-07-20 13:12 UTC, thearchit3ct commented on tests/broker-engine/victoria.robot
> +    config_broker_victoria_output
```suggestion
    Config Broker Victoria Output
```

2023-07-20 13:12 UTC, thearchit3ct commented on tests/broker-engine/victoria.robot
> +            ${status_found}    check_victoria_status
```suggestion
            ${status_found}    Check Victoria Status
```

2023-07-20 13:12 UTC, thearchit3ct commented on tests/broker-engine/victoria.robot
> +    ${start}    get_round_current_date
```suggestion
    ${start}    Get Round Current Date
```

2023-07-20 13:12 UTC, thearchit3ct commented on tests/broker-engine/victoria.robot
> +            ${status_found}    check_victoria_status
```suggestion
            ${status_found}    Check Victoria Status
```

2023-07-20 13:12 UTC, thearchit3ct commented on tests/broker-engine/victoria.robot
> +            ${status_found}    check_victoria_status
```suggestion
            ${status_found}    Check Victoria Status
```

2023-07-20 13:12 UTC, thearchit3ct commented on tests/broker-engine/victoria.robot
> +    ${start}    get_round_current_date
```suggestion
    ${start}    Get Round Current Date
```

2023-07-20 13:12 UTC, thearchit3ct commented on tests/broker-engine/victoria.robot
> +            ${metric_found}    check_victoria_metric
```suggestion
            ${metric_found}    Check Victoria Metric
```

2023-07-20 13:12 UTC, thearchit3ct commented on tests/broker-engine/victoria.robot
> +    ${start}    get_round_current_date
```suggestion
    ${start}    Get Round Current Date
```

2023-07-20 13:12 UTC, thearchit3ct commented on tests/broker-engine/victoria.robot
> +    config_broker_victoria_output
```suggestion
    Config Broker Victoria Output
```

2023-07-20 13:12 UTC, thearchit3ct commented on tests/broker-engine/victoria.robot
> +    config_broker_victoria_output
```suggestion
    Config Broker Victoria Output
```

2023-07-20 13:12 UTC, thearchit3ct commented on tests/broker-engine/victoria.robot
> +    ${start}    get_round_current_date
```suggestion
    ${start}    Get Round Current Date
```

2023-07-20 14:10 UTC, jean-christophe81 commented on tests/broker-engine/victoria.robot
> +    Stop Server
done

2023-07-20 14:12 UTC, jean-christophe81 commented on tests/broker-engine/victoria.robot
> +            ${metric_found}    check_victoria_metric
done

2023-07-21 07:13 UTC, bouda1 approved these changes

2023-07-21 07:26 UTC, thearchit3ct approved these changes

2023-07-21 07:38 UTC, merged

2023-07-21 07:39 UTC, jean-christophe81 commented
REFS:MON-16262