fix(unfied_sql): service and host states are filled at startup with r…
centreon/centreon-collect pull request #853
Opened 2023-08-23 13:54 UTC by jean-christophe81

## Description

**Fixes** # (issue)

real_state is copied in state in services and hosts tables at restart even if real_state is null

## Type of change

- [X] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 21.10.x
- [ ] 22.04.x
- [ ] 22.10.x
- [ ] 23.04.x
- [X] 23.10.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

## Checklist

- [ ] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

2023-08-23 15:23 UTC, thearchit3ct commented on tests/broker/start-stop.robot
> +    ${start}=    Get Current Date
```suggestion
    ${start}    Get Current Date
```

2023-08-23 15:23 UTC, thearchit3ct commented on tests/broker/start-stop.robot
> +    ${result}=    Find In Log with Timeout    ${engineLog0}    ${start}    ${content}    60
```suggestion
    ${result}    Find In Log with Timeout    ${engineLog0}    ${start}    ${content}    60
```

2023-08-23 15:23 UTC, thearchit3ct commented on tests/broker/start-stop.robot
> +    ...    msg=An Initial service state on (host_50,service_1000) should be raised before we can start our external commands.
```suggestion
    ...    An Initial service state on (host_50,service_1000) should be raised before we can start our external commands.
```

2023-08-23 15:23 UTC, thearchit3ct commented on tests/broker/start-stop.robot
> +        ${output}=    Query    SELECT state FROM services WHERE enabled=1 AND state IS NULL
```suggestion
        ${output}    Query    SELECT state FROM services WHERE enabled=1 AND state IS NULL
```

2023-08-30 11:43 UTC, bouda1 requested changes

2023-08-30 11:43 UTC, bouda1 commented on tests/broker/start-stop.robot
> +    [Documentation]    restart cbd with unified_sql services state must not be null after restartno deadlock
There is a typo in this documentation.

2023-08-31 15:08 UTC, thearchit3ct approved these changes

2023-08-31 15:09 UTC, merged